### ISSUE TITLE
Unable to initialize vault after creating ssh tunnel

### ISSUE THREAD

**Issue by jasmor** [aws-quickstart/quickstart-hashicorp-vault#10]
Hi,

On step 4 of https://s3.amazonaws.com/quickstart-reference/hashicorp/vault/latest/doc/hashicorp-vault-on-the-aws-cloud.pdf it says to create an ssh tunnel. I did so by doing 
`ssh -L 8200:10.0.3.133:8200 ubuntu@10.0.3.133 -N  `from the bastion host and received this error from my local machine 

> vault init
Error initializing Vault: Put https://127.0.0.1:8200/v1/sys/init: dial tcp 127.0.0.1:8200: getsockopt: connection refused

**Comment by tonynv** [comment]
Pull upstream changes for linux-bastion https://github.com/aws-quickstart/quickstart-hashicorp-vault/commit/521d27417d581746d8f89c40a3222e3315a7e4dc  
All test are passingnow . Please reopen if this issue presists
