### ISSUE TITLE
Errors with Linux Bastion stage of Hashi quickstart for a new VPC

### ISSUE THREAD

**Issue by scottbward** [aws-quickstart/quickstart-hashicorp-vault#11]
When launching the hashi vault quickstart for a new VPC I am getting errors during the linux bastion host stage of the overall deployment.  The stack for the linux bastion host is erroring out at the BastionAutoScalingGroup resource with the message "Received 1 FAILURE signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement".  Even though this message happens the EC2 instance for the AutoScaling group successfully launches.  

I have tried launching this quickstart in the us-east-1 and us-west-2 regions with the same results.  

I also tried just launching the linux bastion quickstart on its own.  I used the same S3 bucket and prefix parameters as the Hashi quickstart is passing in and the quickstart fails with the same error.  If I launch the linux bastion quickstart using the default AWS parameters then the quickstart for the linux bastion host launches successfully.

I was able to successfully launch the Hashi vault quickstart back at the beginning of April so have not always seen this error.  

Let me know if there is any more info I can provide which will help.

**Comment by tonynv** [comment]
@scottbward  Fixes are here and here https://github.com/aws-quickstart/quickstart-hashicorp-vault/commit/e28da24f6f83f605975b2257ad33e6326bb7bb2b https://github.com/aws-quickstart/quickstart-hashicorp-vault/commit/7199520a24e2a4c77d3c3126408e38a1ab036e88
Please give it a try and update this ticket as needed.

**Comment by tonynv** [comment]
@scottbward  My tests are passing.  https://s3.amazonaws.com/aws-quickstart-reports/develop/quickstart-hashicorp-vault/index.html
Let me know if you can launch successfully now.

**Comment by tonynv** [comment]
This issue was resolved in the commit listed above. Closing
