### ISSUE TITLE
Cannot ssh from bastion host to any of the other instances

### ISSUE THREAD

**Issue by esyd1pi0** [aws-quickstart/quickstart-hashicorp-vault#12]
I get the _Permission denied (publickey)_ error when I ssh from bastion host to any of the other instances.

**Comment by tonynv** [comment]
you need to setup ssh forwarding 
`ssh-add`
then ssh to the bastion with the `-A` flag (see deployment guide for more info)

https://aws-quickstart.s3.amazonaws.com/quickstart-hashicorp-vault/doc/hashicorp-vault-on-the-aws-cloud.pdf
See -> Step 3. Access Consul via SSH

**Comment by christopinka** [comment]
I got this working, however the quickstart guide I believe needs updating. I ended using this:

```Bash

ssh -A -i ".ssh/vault-vpc.pem" ubuntu@ec2-[eip].compute-1.amazonaws.com

```

where vault-vpc.pem is the key I created for the vpc and set to chmod 400

**Comment by christopinka** [comment]
Also, very unclear

"4. Repeat the vault unseal command for the second Vault server node (using
VaultNode2PrivateIp) to unseal the second Vault server and to activate Vault’s high
availability mode."

**Comment by gargana** [comment]
Thanks for this feedback. We are currently working towards an update of the documentation and the Quick Start itself. I will be sure to incorporate this feedback to improve the documentation and experience.

**Comment by christopinka** [comment]
Sure thing. Thanks for all the great tutorials, etc. you have. I still don't know what "VaultNode2PrivateIp" is but I figured out unsealing the standby and getting HA mode. It's the same as for the first vault instance only skip ```$ vault init``` and just use the keys and token you already have.
