### ISSUE TITLE
Log Group not unique

### ISSUE THREAD

**Issue by rohanshirke** [aws-quickstart/quickstart-hashicorp-vault#13]
We would like to deploy Vault in the same VPC for which we would like to have Log group name to be unique.

**Comment by tonynv** [comment]
Fixed in https://github.com/aws-quickstart/quickstart-hashicorp-vault/commit/4024758fffa90fff2efbc371e8335295d27105f0

**Comment by tonynv** [comment]
@rohanshirke  Latest release contains the fixes you requested.
