### ISSUE TITLE
HashiCorpConsulStack fails to create due to required parameters having no values

### ISSUE THREAD

**Issue by dlobue** [aws-quickstart/quickstart-hashicorp-vault#14]
Here's the exact error I get:
```
Parameters: [PublicSubnet3CIDR, PrivateSubnet2CIDR, AccessCIDR, PrivateSubnet1CIDR, PublicSubnet2CIDR, PublicSubnet1ID, PublicSubnet2ID, PrivateSubnet3CIDR, PublicSubnet3ID, PublicSubnet1CIDR] must have values
```

All those parameters do have values though:
```
AccessCIDR	0.0.0.0/0	
PrivateSubnet1CIDR	10.0.0.0/19	
PrivateSubnet2CIDR	10.0.32.0/19	
PrivateSubnet3CIDR	10.0.64.0/19	
PublicSubnet1CIDR	10.0.128.0/20	
PublicSubnet2CIDR	10.0.144.0/20	
PublicSubnet3CIDR	10.0.160.0/20
```

Almost forgot: I'm kicking this off from https://aws.amazon.com/quickstart/architecture/vault/ and am using the "Deploy into new VPC" option.

**Comment by dlobue** [comment]
I found the issue: the default values for the quick start s3 bucket name and key prefix are referring to an older version of the templates.

Using the below values should fix the issue:
```
QSS3BucketName	aws-quickstart	
QSS3KeyPrefix	quickstart-hashicorp-vault/	
```

**Comment by tonynv** [comment]
Please re open if you have any further issues

**Comment by tonynv** [comment]
FYI
https://github.com/aws-quickstart/quickstart-hashicorp-vault/releases/tag/v3.0
