### ISSUE TITLE
Consul is not installed on the Vault servers

### ISSUE THREAD

**Issue by earchibald-lv** [aws-quickstart/quickstart-hashicorp-vault#24]
Contrary to the documentation provided with the Quickstart, consul is NOT installed on the Vault servers. This causes Vault startup to fail (it's pointed at 127.0.0.1).

There are only two Vault servers started; the documentation shows three.

There is only one bation host created; the documentation shows two.

The Vault HA API and Cluster addresses point at an ENI that won't attach.

What gives? This quickstart is nonfunctional as shipping.

**Comment by tonynv** [comment]
Thanks for reporting this issues is being worked here https://github.com/aws-quickstart/quickstart-hashicorp-vault/issues/19.
