### ISSUE TITLE
Only one bastion host is created. Documentation shows two.

### ISSUE THREAD

**Issue by earchibald-lv** [aws-quickstart/quickstart-hashicorp-vault#25]
The documentation illustrates a bastion host being created in public subnets 1 and 2, but there is only one created (in public subnet 2):

![Screen Shot 2019-10-17 at 12 52 03 PM](https://user-images.githubusercontent.com/34492938/67042587-055e1000-f0dd-11e9-807b-87c872b15b85.png)

**Comment by tonynv** [comment]
Diagram has been updated  
a8fe59d Exposes the `NumBastionHosts` parameter in the master template so a second bastion can be requested at launch. (staged in release milestone **0.10.4.fix**)
