### ISSUE TITLE
Update to vault 1.4.0 including best practices

### ISSUE THREAD

**Issue by gargana** [aws-quickstart/quickstart-hashicorp-vault#39]
Update to vault 1.4 including best practices

**Comment by dcallao** [comment]
I pushed some changes to the sandbox repo. I started this repo to test best practices. This is the very initial commit which will be replicated into this issue: https://github.com/dcallao/vault-quickstart-dev

 I expect to submit a PR by tomorrow if not early next week.

**Comment by gargana** [comment]
Closing since this is complete
