### ISSUE TITLE
Allow for selection of CIS Ubuntu Linux 16.04 LTS Benchmark or a base image

### ISSUE THREAD

**Issue by gargana** [aws-quickstart/quickstart-hashicorp-vault#41]
Allow for selection of CIS Ubuntu Linux 16.04 LTS Benchmark or a base image

**Comment by dcallao** [comment]
@gargana Lets stick to CIS Ubuntu 16.04 LTS. My sandbox dev env runs on 18.04 but we are going to leave this QuickStart on Ubuntu 16.04 LTS.

**Comment by gargana** [comment]
Closing since this is complete
