### ISSUE TITLE
vault init does not seem to work

### ISSUE THREAD

**Issue by vikashvverma** [aws-quickstart/quickstart-hashicorp-vault#42]
After login from bastion to vault machine, `consul member` command works. However when running the vault init after exporting `VAULT_ADDRESS`, it produces error.

<img width="557" alt="Screenshot 2020-03-04 at 6 46 59 PM" src="https://user-images.githubusercontent.com/915277/75883904-ce00bd80-5e49-11ea-926c-4555d0938b51.png">

**Comment by dcallao** [comment]
Please use this command instead: `vault operator init`. See https://www.vaultproject.io/docs/commands/operator/init/

**Comment by vikashvverma** [comment]
I used `vault operator init` as well and it produced the same error except the warning.

**Comment by vikashvverma** [comment]
@dcallao Here is the screenshot that this does not seem to work.
<img width="604" alt="Screenshot 2020-05-08 at 3 12 22 PM" src="https://user-images.githubusercontent.com/915277/81393688-69f6c000-913e-11ea-80a2-ecda052dca5c.png">

**Comment by dcallao** [comment]
@vikashvverma This no longer applies. Vault QSG has been upgraded and initialization works as expected.
