### ISSUE TITLE
Vault stack creation fails in a new VPC

### ISSUE THREAD

**Issue by vikashvverma** [aws-quickstart/quickstart-hashicorp-vault#57]
The vault stack creation fails in new VPC

Parameters:

<img width="1792" alt="Screenshot 2020-05-08 at 5 10 58 PM" src="https://user-images.githubusercontent.com/915277/81402404-f8733d80-914e-11ea-9062-fcc3cc889799.png">

Events:
<img width="1792" alt="Screenshot 2020-05-08 at 5 10 48 PM" src="https://user-images.githubusercontent.com/915277/81402432-02953c00-914f-11ea-891f-9c49e8cf510d.png">

**Comment by gargana** [comment]
Hi Vikashvverma. 

In my experience if the LinuxBastionHostStack fails it tends to be from a lack of available EIP addresses in the region in which you are launching. If you can filter (Failed/Deleted) stacks you should be able to see the specific error on the LinuxBastionHostStack stack itself.

Also please note we have released a brand new version of the Quick Start so I recommend taking a look at launching the new version.

**Comment by gargana** [comment]
Closing this issue out for now.
