### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by jhmartin** [aws-quickstart/quickstart-hashicorp-vault#67]
https://github.com/aws-quickstart/quickstart-hashicorp-vault/blob/master/scripts/bootstrap_server.sh#L62-L71

The echo does not use the correct variable name.

**Comment by gargana** [comment]
Thanks for pointing this out.
I would like to just confirm that you are talking about the two lines:
`echo instance_id_array $instance_id_array`
and
`echo instance_ip_array $instance_ip_array`

They should be outputting the entire array like this:
`echo instance_id_array ${instance_id_array[@]}`
and
`echo instance_ip_array ${instance_ip_array[@]}`

From these lines: https://github.com/aws-quickstart/quickstart-hashicorp-vault/blob/master/scripts/bootstrap_server.sh#L59-L71

**Comment by jhmartin** [comment]
I should have specified the exact text :< I recall it was just a simple spelling error, but now that I look at it again I don't see it so perhaps I just misread it.
