### ISSUE TITLE
Add gpg verification to downloaded install_vault bash script

### ISSUE THREAD

**Issue by xntrik** [aws-quickstart/quickstart-hashicorp-vault#68]
As per the Archive Checksum Verification section on https://www.hashicorp.com/security the install_vault function in https://github.com/aws-quickstart/quickstart-hashicorp-vault/blob/master/scripts/functions.sh should be updated with the following.

Some variables and other files will need to be downloaded during installation, so the below is somewhere between bash snippets and pseudocode.

* Set a variable to the PGP public key `readonly vault_gpg_key="..."`
* Import the key into gpg `echo -e "${vault_gpg_key}" | gpg --import -`
* Download the appropriate SHA256SUMS file and SHA256SUMS.sig file for the version of vault
* Verify the SHA256 sig `gpg --batch --verify "vault_${vault_version}_SHA256SUMS.sig" "vault_${vault_version}_SHA256SUMS"`
* Validate the SHA256 of the individual downloaded vault ZIP file `grep "${vault_filename}" "vault_${vault_version}_SHA256SUMS" | sha256sum -c`

**Comment by gargana** [comment]
Thanks for pointing this out. I will work on an update.

**Comment by xntrik** [comment]
Thanks @gargana !

**Comment by gargana** [comment]
working on a PR for this today.

**Comment by gargana** [comment]
All tests passed code merge into main branch complete. Closing this out.
