### ISSUE TITLE
Update to latest Vault version

### ISSUE THREAD

**Issue by RealDrewKlayman** [aws-quickstart/quickstart-hashicorp-vault#76]
Vault is currently on version `1.5.3`.

This currently only allows for version `1.4`

Possibly add the ability to specify `latest` as a version?

**Comment by gargana** [comment]
I will be working on adding latest versions and hopefully they will be available shortly.
latest may cause problems in that bootstrapping may need to change along with newer versions.

**Comment by RealDrewKlayman** [comment]
@gargana Thank you so much!

I really appreciate your work on this project.

**Comment by gargana** [comment]
Now supporting the latest 1.4.6 and 1.5.3 versions.
