### ISSUE TITLE
Can we get the submodule quickstart-aws-acm-certificate updated to get python37 upgrade?

### ISSUE THREAD

**Issue by sr75** [aws-quickstart/quickstart-hashicorp-vault#87]
Need submodule quickstart-aws-acm-certificate updated to get python37 update

Repo currently points to https://github.com/aws-quickstart/quickstart-aws-acm-certificate/blob/17e712a6989e9fb514b293eb61fd90870f98629a/templates/quickstart-aws-acm-certificate.template.yml#L164

Latest quickstart-aws-acm-certificate has py3 updated:

https://github.com/aws-quickstart/quickstart-aws-acm-certificate/blob/main/templates/quickstart-aws-acm-certificate.template.yml#L173

**Comment by gargana** [comment]
Will work on this update today. Waiting on CI tests to pass for two other changes first.
