### ISSUE TITLE
Ubuntu 16.04 LTS (Long Term Support) period will end on Friday, April 30, 2021 

### ISSUE THREAD

**Issue by sr75** [aws-quickstart/quickstart-hashicorp-vault#88]
Ubuntu 16.04 LTS (Long Term Support) period will end on Friday, April 30, 2021 

Can we get the template updated to use either Ubuntu 18.04 LTS or Ubuntu 20.04 LTS?

**Comment by gargana** [comment]
I am working on this today, I will add 20.04 LTS for both the Ubuntu base and CIS images
