### ISSUE TITLE
QuickStart Vault - documentation on ssh tunnel

### ISSUE THREAD

**Issue by vsnyc** [aws-quickstart/quickstart-hashicorp-vault#9]
Reported at [Forum link](https://forums.aws.amazon.com/thread.jspa?threadID=255054)

On step 4 of the pdf - https://s3.amazonaws.com/quickstart-reference/hashicorp/vault/latest/doc/hashicorp-vault-on-the-aws-cloud.pdf

To initialize vault it says to start a ssh tunnel between your workstation and the bastion host.
I just wanted to point out that the sshd config on the bastion host has AllowTcpForwarding set to no, so this step will not work until changing that and restarting ssh.
Wonder if that should be added to the documentation, or the default 

Solution:
We should `"EnableTCPForwarding": "true"` to `BastionStack` in `quickstart-hashicorp-vault-master.template`

**Comment by tonynv** [comment]
@vsnyc Fixed in https://github.com/aws-quickstart/quickstart-hashicorp-vault/commit/17f45deb6eac192c61fada3cef682fb379ee7c2b

**Comment by jasmor** [comment]
I'm having an issue with step 4. I've created the SSH tunnel from my local machine to the bastion host but unable to initialize the vault: 
`ssh -D 8200 -f -C -q -N ubuntu@ec2instance-example.com 
export VAULT_ADDR=http://127.0.0.1:8200
vault init
Error initializing Vault: Put http://127.0.0.1:8200/v1/sys/init: EOF
`

I can confirm the tunnel is created by:
`netstat -an | grep 8200
tcp4       0      0  127.0.0.1.8200         *.*                    LISTEN     
tcp6       0      0  ::1.8200               *.*                    LISTEN`
