### ISSUE TITLE
chicken and egg problem

### ISSUE THREAD

**Issue by apicloudguru** [aws-quickstart/quickstart-hashicorp-vault#98]
The CFT requires parameters for the hosted domain or zone id, but those can't be created yet because it requires a VPC. Using the deploy to new VPC approach, the VPC doesn't exist yet, so we can't create the zone.

**Comment by gargana** [comment]
There appears to be some confusion around what Zone is being required. The ZoneId is a [R53 HostedZone](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53-hostedzone.html) and a valid DomainName which can be added to that HostedZone.

ie:
`DomainName:` consul.some.domain.org
`HostedZoneID:` "Z3AUXXXXXDIKK"
